"""Player repository protocol and legacy SQLite constructor."""

from __future__ import annotations

from typing import Protocol

from storyloop_platform.adapters.sql_database import open_database, sqlite_url, upgrade_database
from storyloop_platform.portal.models import SaveRecord
from storyloop_platform.portal.sql_repository import SQLPlayerRepository


class PlayerRepository(Protocol):
    def register(self, username: str, password: str, invite_code: str | None = None,
                 *, require_invite: bool = False) -> str: ...
    def authenticate(self, username: str, password: str) -> str: ...
    def issue_token(self, player_id: str) -> str: ...
    def resolve_token(self, token: str) -> str: ...
    def revoke_token(self, token: str) -> None: ...
    def create_save(self, player_id: str, catalog_id: str, game_id: str,
                    package_id: str, package_version: str, package_hash: str,
                    play_mode: str | None = None) -> SaveRecord: ...
    def get_save(self, player_id: str, game_id: str) -> SaveRecord: ...
    def list_saves(self, player_id: str) -> tuple[SaveRecord, ...]: ...
    def get_turn_response(self, game_id: str, request_id: str, text: str) -> dict | None: ...
    def latest_turn_response(self, game_id: str) -> dict | None: ...
    def store_intro(self, game_id: str, response: dict) -> None: ...
    def get_intro(self, game_id: str) -> dict | None: ...
    def list_turns(self, game_id: str) -> list[dict]: ...
    def store_turn_response(self, game_id: str, request_id: str, text: str,
                            response: dict) -> None: ...


class SQLitePlayerRepository(SQLPlayerRepository):
    """Compatibility entry point backed by the shared SQL repository."""

    def __init__(self, path: str) -> None:
        self.path = path
        url = sqlite_url(path)
        upgrade_database(url)
        super().__init__(open_database(url))
